// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[location].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/createExhibit.ts";
import * as $5 from "./routes/create.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Popup.tsx";
import * as $$1 from "./islands/TextArea.tsx";
import * as $$2 from "./islands/form.tsx";

const manifest = {
  routes: {
    "./routes/[location].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/createExhibit.ts": $4,
    "./routes/create.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Popup.tsx": $$0,
    "./islands/TextArea.tsx": $$1,
    "./islands/form.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
